version: "3.8"
services:
  web:
    build: .
    container_name: fastapi_web
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - BROKER_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydatabase
    depends_on:
      - redis
      - db
    # no volumes for prod; add if you want live reload
    # volumes:
    #   - .:/app

  worker:
    build: .
    container_name: celery_worker
    command: >
      celery -A workers.db_saver_celery_worker worker --loglevel=info
    environment:
      - BROKER_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydatabase
    depends_on:
      - redis
      - db
      - web

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  db:
    image: postgres:13-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    # volumes:
    #   - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata:
