name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set image name and tag
        id: vars
        run: |
          echo "IMAGE_NAME=sundess17/12factorapp_sentimentanalyzer" >> $GITHUB_ENV
          echo "TAG=$(date +%s)" >> $GITHUB_ENV

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME:$TAG

      - name: Push image to Docker Hub
        run: docker push $IMAGE_NAME:$TAG
