name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push image to Docker Hub
        run: |
          IMAGE_NAME=myusername/my-image-name
          TAG=$(date +%s)
          docker tag my-image-name:$TAG $IMAGE_NAME:$TAG
          docker push $IMAGE_NAME:$TAG
